### ISSUE TITLE
LiCSBAS-Comet

### ISSUE THREAD

**Issue by araditiya** [comet-licsar/licsbas_dev_obsolete#1]
This is a general question, I guess. 
What is the specific different between comet-licsbas and the author's one (yumorishita/LiCSBAS)

**Comment by espiritocz** [comment]
hi araditiya,
this version is one actively developed by the COMET Leeds group, on top of the original codes by Dr. Yu Morishita.
note we keep the core functionality unchanged (as the original codes already contain full-range processing chain).

to know more, you may check for our COMET InSAR Workshop (this week)
